name: serializable_data
description: A starting point for Dart libraries or applications.
version: 1.0.2
# homepage: https://www.example.com
publish_to: 'none'
environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  email_validator: ^2.0.1
  injector: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
